o2_ui_welcome:
    pattern:  /welcome
    defaults: { _controller: 'O2UIBundle:Default:index' }

o2_ui_twbs_form_theming:
    pattern: /twbs-form-theming
    defaults: { _controller: 'O2UIBundle:Theming:formTheming' }
    
o2_ui_twbs_component_theming:
    pattern: /twbs-component-theming
    defaults: { _controller: 'O2UIBundle:Theming:componentTheming' }